#!/bin/sh
#
# This script is run after receive-pack has accepted a pack and the
# repository has been updated.  It is passed arguments in through stdin
# in the form
#  <oldrev> <newrev> <refname>
# For example:
#  aa453216d1b3e49e7f6f98441fa56946ddcd6a20 68f7abf4e6f922807889f52bc043ecd31b79f814 refs/heads/master
#
# see contrib/hooks/ for an sample, or uncomment the next line (on debian)
#

set -e

let max=1024*1024
count=0
echo "Checking file sizes..."
while read oldrev newrev refname
do
	# echo $oldrev $newrev $refname
	# skip the size check for tag refs
	if ! [[ ${refname} =~ ^refs/tags/* ]]
	then
		
		rawdiff=$(git diff --raw ${oldrev} ${newrev})
		while read oldmode newmode oldsha newsha code fname
		do
			echo -n "${fname}"
			newsize=$(git cat-file -s ${newsha%\.\.\.})
			if (( ${newsize} > ${max} ))
			then
				echo " size ${newsize}B > ${max}B"
				let "count+=1"
			else
				echo " ok"
			fi
		done <<< "${rawdiff}"
	fi
	
done

exit ${count}

